### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by blzbruno** [dcode/http-bot#1]
I tried to run but in console

```
Read 1 entries.
Traceback (most recent call last):
  File "http_gauss_browse.py", line 73, in <module>
    mainloop(sys.argv)
  File "http_gauss_browse.py", line 60, in mainloop
    url = "http://www.%s" % alexa_sites[offset].split(',')[1].strip()
IndexError: list index out of range


```

can you help me?

**Comment by dcode** [comment]
Can you share the commands you used to pull the Alexa list and how you ran this script?

**Comment by blzbruno** [comment]
Sorry everthing is okay was missing lxml

So I can try do generate "fake" traffic to a webpage with this tool?

**Comment by dcode** [comment]
I use this to generate "fake" user browsing traffic. I wanted to model how a user might browse the web, purely to analyze the traffic patterns. You can run/tweak this tool on one or more boxes to generate network traffic. If you just wanted to browse one website, you can put a single URL in the list (instead of the generated Alexa 500 list). The first stage of each round is to pull the URL listed, then enumerate all links on that page, and randomly select one. After it does this a few times, it will go back to the top of the list.

**Comment by blzbruno** [comment]
Thanks
